### ISSUE TITLE
Can't run or compile on Ubuntu 22.04

### ISSUE THREAD

**Issue by alvv-z** [Admiral-Fish/PokeFinder#337]
When I try to run PokeFinder, I get the following error in the command line:
`./PokeFinder: symbol lookup error: /lib/x86_64-linux-gnu/libbrotlidec.so.1: undefined symbol: _kBrotliPrefixCodeRanges`.

When compiling I get the following:
```
[...]
[ 98%] Linking CXX executable PokeFinder
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1: undefined reference to `BrotliDefaultAllocFunc'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1: undefined reference to `_kBrotliContextLookupTable'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1: undefined reference to `BrotliDefaultFreeFunc'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1: undefined reference to `_kBrotliPrefixCodeRanges'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Source/CMakeFiles/PokeFinder.dir/build.make:569: Source/PokeFinder] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:260: Source/CMakeFiles/PokeFinder.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by Admiral-Fish** [comment]
I am able to compile/build just fine on 22.04, did you follow the build instructions?

**Comment by alvv-z** [comment]
Yeah, I've no clue what could be wrong. My process is:
 1. `sudo apt install qt6-base-dev qt6-tools-dev qt6-tools-dev-tools qt6-l10n-tools`
 2. `sudo apt install build-essential libgl1-mesa-dev`
 3. `git submodule update --init` (CMake threw errors when building before running this with `--init`)
 4. `mkdir build`
 5. `cd build`
 6. `cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE  ../`
 7. `cmake --build .`

**Comment by Admiral-Fish** [comment]
My CI builds are now on Ubuntu 22.04 and working just fine. Looking around online all I can find mention order of things linking. Closing since this seems to be an environment issue and not a problem with Pokefinder itself.
